# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pin',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
