# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20180207_2042'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='TransactionItem',
        ),
    ]
