# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20180207_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
