# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_transactionitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='transactionitem',
            name='quantity',
        ),
    ]
