# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 18:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0006_auto_20180207_2139'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transactionitem',
            unique_together=set([('recepient', 'product')]),
        ),
    ]
